Comfy-Org/desktop

package.json
Issue: https://github.com/Comfy-Org/desktop/issues/380
Getting reports of python failing to be installed / extracted. 
Seems to be related to: https://github.com/astral-sh/uv/issues/6331. Some people have confirmed that retrying works, which was added in `uv 0.5.4`
https://github.com/astral-sh/uv/pull/9274
=> Upgrade uv to 0.5.4

src/services/sentry.ts
=> Show preview of error in pop up.

.github/ISSUE_TEMPLATE/bug-report.yaml
The electron app does not have a browser env issue.
=> Remove browser section in bug-report template

.github/actions/build/windows/todesktop/action.yml, .github/workflows/publish_staging.yml
Forgot to modify the `Publish Staging Application` command to use yarn publish:staging.
=> Fixed: Run yarn publish:staging

package.json, vite.main.config.ts, yarn.lock
See decoded error e.g. [here](https://comfy-org.sentry.io/issues/6103448285/?project=4508007940685824&query=release%3AComfyUI%400.3.23-test&referrer=release-issue-stream)
=> feat: Upload sourcemaps to Sentry

src/main-process/comfyServer.ts, src/utils.ts
- Fixes bug in log rotation that resulted in only the most recent log being stored
- Adds maximum log count - default 50
- All filesystem access is now async
- Currently no limit on file size
=> Add async log rotation with max files

src/virtualEnvironment.ts
Fixes paths with spaces in
Swaps win32 from using bat (doesnt work in powershell) to ps1 script, bypassing execution policy
=> Fix activating venv in integrated terminal

scripts/resetInstall.js, src/install/installationValidator.ts, src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts, src/main.ts, src/store/desktopConfig.ts, src/store/index.ts, src/store/store.ts
Adds an electron-store config store to house desktop-specific installation state / config.  Includes fairly(?) complete error handling and pre-window interaction.
```json
{
"basePath": "C:\\Users\\User\\Documents\\ComfyUI",
"installState": "installed"
}
```
- Install state is `undefined` until an install has started, `'started'`, or `'installed'`.
- `'upgraded'` status is temporarily used when upgrading from a version prior to this PR, and changed to `'installed'` when successful
- Base path is set immediately before the install process starts
- The `base_path` in `extra_models_config.yaml` is still the source of truth
- `basePath` in config.json is used as a fallback only
If the settings store is invalid (file is present, but can't be parsed as json), the user is prompted to resolve the …
=> Settings store

global.d.ts, src/preload.ts, vite.base.config.ts
This PR adds `getComfyUIVersion` api endpoint to get ComfyUI version, as the built-in server side ComfyUI version endpoint requires the app to be hosted in a Git repo, while the electron app is not shipped with ComfyUI's git repo.
=> Add api.getComfyUIVersion

scripts/resetInstall.js, src/config/comfyServerConfig.ts, src/install/installationValidator.ts, src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts, src/main.ts, src/store/desktopConfig.ts, src/store/index.ts, tests/unit/comfyServerConfig.test.ts
Allow user to see result of YAML config read
- Nature of the failure is returned
- Invalid values read are included if available
- Retains inferred types
When the file exists but base_path is just invalid:
- In this PR, it pretends the file doesn't exist and reinstalls
- Should be connected to the UI path picker, once finalised
=> Reland #362 - improved startup error handling

src/config/comfySettings.ts, src/store/desktopConfig.ts
- Removes `set` method from the ComfyUI core settings reader
- Unused, and there is no write method so it seems misleading
- Adds guards for permission / filesystem errors
- Converts to async FS access
=> Limit access to core settings

src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts
- Requires #362
This simply has different window sizes for the install process:
- Window starts centred on screen, 1024 x 768
- User runs through the install process
- Window is maximised as the final step of installation
- Also increases the window min size to 640 x 640
- No effect if the user has moved or altered the window before in any way
=> Installer window

src/main-process/comfyDesktopApp.ts, src/shell/terminal.ts, src/shell/util.ts, src/virtualEnvironment.ts
Closes: https://github.com/Comfy-Org/desktop/issues/398
=> Use zsh when running uv in VirtualEnv for macOS.

src/main-process/appWindow.ts, src/main-process/comfyServer.ts, src/main.ts
Follow-up on https://github.com/Comfy-Org/desktop/pull/465
This PR makes host and port configurable in the frontend server config panel.
=> Make port and host configurable with setting.launchArgs

.husky/pre-commit, package.json
Yarn only supports postinstall.
https://typicode.github.io/husky/how-to.html#manual-setup
https://yarnpkg.com/advanced/lifecycle-scripts
=> Fixed: Husky precommit hook with yarn

src/main-process/comfyDesktopApp.ts, src/main-process/comfyServer.ts, src/services/backup.ts, src/utils.ts
Strips all escape codes from wrapped-process output logs.
```log
[2024-12-12 23:55:59.116] [info]  [?25l[37m[H⠸ [m[2mResolving dependencies...                                                     [K[?25h[1;134H
[2024-12-12 23:55:59.135] [info]  [?25l[22m[1;80H[?25h
[2024-12-12 23:55:59.309] [info]  [?25l[37m[H⠸ [m[2maiohappyeyeballs==2.4.3                                                       [K[?25h[1;136H
[2024-12-12 23:55:59.328] [info]  [?25l[22m[37m[H⠼ [m[2maiohappyeyeballs==2.4.3                                                       [K[?25h[1;136H
```
```log
[2024-12-12 23:55:59.116] [info]  ⠸ Resolving dependencies...                                                     
[2024-12-12 23:55:59.135] [info]  
[2024-12-12 23:55:59.309] [info]  ⠸ …
```
=> Improve log legibility

src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts, src/main.ts, src/store/desktopConfig.ts, src/store/index.ts
- Improves separation of concerns in `DesktopConfig`
- Refactors to `use()` pattern
- Converts / removes static accessors
Intention is to require less future-effort.  No libraries I checked use static classes for this kind of thing.
=> [Refactor] Improve separation of concerns / lifecycle

src/handlers/appInfoHandlers.ts, src/install/installationValidator.ts, src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts, src/main-process/comfyServer.ts, src/main.ts, src/preload.ts, src/store/desktopConfig.ts, src/store/index.ts, src/virtualEnvironment.ts
- Based on #482
- Fixes _most_ unawaited async calls
- Remaining unhandled promises are inside synchronous callbacks
- One solution is to just catch & report errors via API to frontend
- Fixes use of async callbacks in functions that do not support async
=> Fix async not awaited

src/utils.ts
Regex escape codes need second escape due to use of string template (originally written as a regex literal).
=> Fix log files not rotated

src/handlers/pathHandlers.ts, src/install/installationValidator.ts, src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts, src/main.ts, src/models/DownloadManager.ts, src/preload.ts, src/services/sentry.ts, src/virtualEnvironment.ts
- Based on #484
- Adds startup error logs, ensuring app lifecycle can be properly traced in `main.log`
- Removes unused vars
- Removes explicit `any`
- TS types
- Various nits
=> Code cleanup, logging

builder-debug.config.ts, package.json, scripts/preMake.js, src/main-process/appWindow.ts, tsconfig.json, vite.main.config.ts
- toDesktop auto update calls use CommonJS require()
- Partially reverts #491
- Limitation on `preMake.cjs` resolved - now also an ES module, extension changed to `.js`
- `main.js` output script is now `main.cjs`
- `preload.cjs` now works as an ES Module - `preload.mjs`
- `.mjs` ext is [an Electron requirement](https://www.electronjs.org/docs/latest/tutorial/esm#esm-preload-scripts-must-have-the-mjs-extension)
┆Issue is synchronized with this [Notion page](https://www.notion.so/497-Fix-crash-on-load-when-not-using-cjs-output-15f6d73d365081c5839be8a60e369e6e) by [Unito](https://www.unito.io)
=> Fix crash on load when not using cjs output

package.json
Automated frontend update to 1.6.1
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-532-chore-Update-frontend-to-1-6-1-1606d73d3650812e9135e7e89c9ae8b6) by [Unito](https://www.unito.io)
=> [chore] Update frontend to 1.6.1

src/virtualEnvironment.ts
`zsh` parses hyphen inside double-quoted arguments as a command argument, not a string.
Just use a different prefix.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-543-Fix-cannot-install-on-macOS-with-certain-zsh-config-1626d73d36508111abe4c38db919c90d) by [Unito](https://www.unito.io)
=> Fix cannot install on macOS with certain zsh config

src/shell/terminal.ts, src/virtualEnvironment.ts
Use OS-specific EOL at the end of every terminal command, more closely emulating real keyboard input.
This is expected to resolve lockups during install caused by interpretation of argument boundaries.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-545-Fix-install-hangs-on-terminal-commands-1626d73d36508127b3bad6342bc5d89d) by [Unito](https://www.unito.io)
=> Fix install hangs on terminal commands

src/main.ts
- Adds error handling specific to python server startup
- Shows OS-native unhandled error message rather than silent quit
- Skips this if already quitting
- Fixes errors not shown in terminal (missing EOL)
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-551-Improve-startup-error-reporting-handling-1646d73d3650815692aacaa9178e3611) by [Unito](https://www.unito.io)
=> Improve startup error reporting / handling

src/preload.ts
Lower log level of terminal output to debug
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-552-Prevent-browser-console-log-spam-1656d73d36508171aef4dc7d68c15226) by [Unito](https://www.unito.io)
=> Prevent browser console log spam

playwright.setup.ts, scripts/prepareTypes.js, src/config/comfyConfigManager.ts, src/handlers/pathHandlers.ts, src/install/installWizard.ts, src/install/installationManager.ts, src/main.ts, src/preload.ts, tests/unit/comfyConfigManager.test.ts
- ComfyUI is no longer forcefully appended to the install path selected by the user
- e.g. Installing to `Documents/ComfyUI`
- Old: `Documents/ComfyUI/ComfyUI`
- New: `Documents/ComfyUI`
- Existing paths can be re-used
- Paired with frontend commit INSERT_PR_HERE
- Electron API Types from this PR are required by the frontend PR 
- Works without the frontend commit, but will not display a warning if the path exists
Default install screen - full install path is now shown in frontend:
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-555-Improve-install-path-selection-UX-1666d73d36508181b406eef0da54bf98) by [Unito](https://www.unito.io)
=> Improve install path selection UX

.github/actions/build/todesktop/action.yml
Removes additional spaces added to start of line in release notes GH action, which breaks MD formatting.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-563-Fix-release-notes-formatting-1676d73d36508149881dfeb6e105b70e) by [Unito](https://www.unito.io)
=> Fix release notes formatting

src/config/comfyServerConfig.ts, src/main-process/comfyDesktopApp.ts, src/store/desktopConfig.ts
- Fixes immediate issue by removing config.json when user confirms reinstall
- Accounts for corruption of state - if config.json is present and extra_models_config.yaml is deleted, the YAML file will be regenerated with defaults
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-565-Fix-reinstall-breaks-config-1676d73d36508116a119c8a9410f3365) by [Unito](https://www.unito.io)
=> Fix reinstall breaks config

package.json
Automated frontend update to 1.6.6
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-566-chore-Update-frontend-to-1-6-6-1676d73d3650811891a7e5ddf990e1ef) by [Unito](https://www.unito.io)
=> [chore] Update frontend to 1.6.6

src/install/installationManager.ts
Sets installed state after first installation.  Install wizard will no longer be shown a second time, during the first time the app is opened after being installed.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-569-Prevent-installer-from-re-running-once-on-first-app-start-1686d73d36508132bef0cd15247bbbe7) by [Unito](https://www.unito.io)
=> Prevent installer from re-running once on first app start

src/virtualEnvironment.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-570-Use-latest-python-3-12-as-default-1686d73d365081d3abf6d446da9144fc) by [Unito](https://www.unito.io)
=> Use latest python 3.12 as default.

src/virtualEnvironment.ts
Current:
- `uv` shell continues running until app is closed
- `kill()` is never called - optional chained after an explicitly `undefined` value
- If fixed to use `pty.kill()`, the EPIPE exception is still raised even with a 10sec timer
Proposed:
- Just kill the process ID
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-558-Fix-uv-shell-never-exits-1666d73d365081438b61e0f133c560ba) by [Unito](https://www.unito.io)
=> Fix uv shell never exits

src/main_types.ts, src/models/DownloadManager.ts
- Allows all API types to be imported
- Removes need to redeclare types in frontend (e.g. via `Parameters<>` decls)
- Fixes a local type import that was using the `main_types` API entry point
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-567-Export-all-API-types-1686d73d365081d3b481f28851890d15) by [Unito](https://www.unito.io)
=> Export all API types

src/constants.ts, src/handlers/appInfoHandlers.ts, src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts, src/main_types.ts, src/models/DownloadManager.ts, src/preload.ts, src/store/desktopSettings.ts
- Requires #567
- Provides API only; screenshots are examples
- Adds OS-native window code for custom window replacement on linux / win32
- Adjusts button size to toolbar
- Transparent background
- Theme-reactive - colours dictated by frontend API
- Enables (WIP) Comfy-Org/ComfyUI_frontend/pull/1856
- No changes to default behaviour
https://github.com/user-attachments/assets/558b80d9-8cdd-48de-8adb-d8f55721bbea
```ts
// Configured in config.json
"windowStyle": "default" | "custom"
```
┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-1964-Add-custom-window-native-window-controls-15f6d73d365081a7901bccad64315f02) by [Unito](https://www.unito.io)
=> Add custom window / native window controls

.github/ISSUE_TEMPLATE/bug-report.yaml
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-572-Add-main-log-upload-steps-to-issue-template-1686d73d3650810cb3f2f9f1888583dc) by [Unito](https://www.unito.io)
=> Add main.log upload steps to issue template

package.json, src/shell/util.ts, yarn.lock
- Resolves root cause of #584
- Implements fixes added in `systeminformation` (see https://github.com/sebhildebrandt/systeminformation/issues/957)
- Resolves various issues caused at different installation states, when PowerShell is not in PATH
- Forces standard env for all users - uses Windows PowerShell even if PS core is default
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-590-Update-package-systeminformation-uses-full-PowerShell-path-1706d73d365081f6a8fbdb903a0b4b68) by [Unito](https://www.unito.io)
=> Update package: systeminformation - uses full PowerShell path

src/constants.ts, src/handlers/appInfoHandlers.ts, src/preload.ts
Follow up on https://github.com/Comfy-Org/desktop/pull/457.
Adds the window style getter as the user setting is not available when the frontend is loaded as static html, i.e. for install pages.
=> Add api.Config.getWindowStyle

src/main-process/appWindow.ts
Guards against exception.  Repro:
1. Change from default window style to `custom` via `setWindowStyle`
2. Send any window controls theme update (change button size / colour)
3. Throws
AppWindow now checks the settings it was created with, rather than the current settings.
Original frontend impl. was incomplete (settings), so the flaw went unnoticed.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-599-Fix-exception-on-window-style-change-1786d73d36508128962ec734d4e7ab13) by [Unito](https://www.unito.io)
=> Fix exception on window style change

src/constants.ts
`ProgressMessages` was moved to the frontend repo in https://github.com/Comfy-Org/ComfyUI_frontend/pull/1831.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-603-Cleanup-Remove-unused-ProgressMessages-1796d73d3650815c9085c75123b71089) by [Unito](https://www.unito.io)
=> [Cleanup] Remove unused ProgressMessages

.env_example, src/main-process/appWindow.ts, src/main.ts
- Can use frontend HMR via vite dev server only when performing installation process / hacky router manipulation
- Attempt to use dev server for both router pages and regular usage (so, everything), provided that:
- `app.isPackaged` is falsy
- `DEV_SERVER_URL` env var is non-nullish
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-600-Allow-dev-server-via-env-when-app-is-unpackaged-1786d73d36508192b7ddd765d826a698) by [Unito](https://www.unito.io)
=> Allow dev server via env when app is unpackaged

src/constants.ts, src/main-process/comfyDesktopApp.ts, src/preload.ts, src/services/sentry.ts
https://github.com/Comfy-Org/ComfyUI_frontend/pull/2229 now directly call Sentry endpoint in the frontend. The electron API for Sentry reporting can be dropped.
=> [Cleanup] Remove electronAPI.sendErrorToSentry

src/handlers/pathHandlers.ts, src/main-process/comfyDesktopApp.ts
Remove unnecessary async wrapping as nothing in the function body is async.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-610-Cleanup-Remove-unnecessary-async-annotation-17b6d73d3650819faa9ce414c07af4b9) by [Unito](https://www.unito.io)
=> [Cleanup] Remove unnecessary async annotation

src/main-process/appWindow.ts
- Double-click on the tray icon has no effect
- Double-click shows the ComfyUI window if hidden
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-614-Add-double-click-restores-ComfyUI-from-system-tray-17b6d73d3650815d9325e830e5b09f4d) by [Unito](https://www.unito.io)
=> Add double-click restores ComfyUI from system tray

scripts/env.mjs
`env.mjs` is not referenced anywhere in the project.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-621-Cleanup-Remove-unused-file-env-mjs-17b6d73d365081b38123c6609a7a480c) by [Unito](https://www.unito.io)
=> [Cleanup] Remove unused file env.mjs

.github/actions/build/linux/app/action.yml, .github/actions/build/windows/app/action.yml, .github/workflows/debug_linux.yml, .github/workflows/debug_macos.yml, src/main.ts, vite.config.ts
https://github.com/Comfy-Org/desktop/pull/468 made device selection decided upon install. This PR removes the build-time device logic on COMFYUI_CPU_ONLY
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-622-Cleanup-Remove-COMFYUI_CPU_ONLY-env-var-17b6d73d365081f99f15d3e3fa110d5d) by [Unito](https://www.unito.io)
=> [Cleanup] Remove COMFYUI_CPU_ONLY env var

package.json, src/constants.ts, src/install/installWizard.ts, src/install/installationManager.ts, src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts, src/main-process/comfyServer.ts, src/main.ts, src/preload.ts, src/services/cmCli.ts, src/services/telemetry.ts, src/virtualEnvironment.ts, tests/unit/telemetry.test.ts, tsconfig.json, yarn.lock
- Queue up events until we know if user opts in or not
- Store unique id in a file on disk
- expose electron api for tracking events
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-617-Draft-Add-optional-usage-metrics-for-installation-onboarding-17b6d73d36508156bce8d82c4a93d0f9) by [Unito](https://www.unito.io)
=> Add optional usage metrics for installation / onboarding.

src/preload.ts
Inline `PropertyDict` type def to avoid introducing mix-panel dependency for type library.
```
export interface PropertyDict {
[key: string]: any;
}
```
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-626-Remove-mix-panel-dependency-on-types-library-17c6d73d365081619421f49b428f734f) by [Unito](https://www.unito.io)
=> Remove mix-panel dependency on types library

src/constants.ts, src/preload.ts, src/services/telemetry.ts, tests/unit/telemetry.test.ts
- if the user property doesn't exist, it will increment from 0
- A negative number will decrement the user property
Can be used to keep a counter belonging to the user.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-630-Add-increment-user-property-electron-API-17d6d73d3650819db901f59438c19653) by [Unito](https://www.unito.io)
=> Add increment user property electron API.

src/install/installationManager.ts, src/main-process/comfyDesktopApp.ts, src/main-process/comfyInstallation.ts, src/main.ts, src/store/desktopSettings.ts
- Fixes TS types
- Adds logging
- Replaces redundant static factory with constructor
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-647-Cleanup-pre-validation-17d6d73d36508143b705fd209048d12a) by [Unito](https://www.unito.io)
=> Cleanup pre validation

src/main-process/appWindow.ts
The line of code was accidentally removed in #600. This PR adds it back.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-649-Revert-workaround-removal-for-dev-server-17d6d73d3650814ea444dbef3db9e546) by [Unito](https://www.unito.io)
=> Revert workaround removal for dev server

src/virtualEnvironment.ts
Issue has no impact on prod, but is a regression.
This is a pre-requisite for validation, which can start and terminate a host shell process multiple times.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-650-Fix-regression-uv-termianl-cannot-be-restarted-17d6d73d3650812dad00ec88dea90f48) by [Unito](https://www.unito.io)
=> Fix regression: uv termianl cannot be restarted

src/virtualEnvironment.ts
EOL is causing cursor placement / minor line overlap issues.
Examples use `\r`:
https://github.com/microsoft/node-pty#example-usage
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-651-Fix-PowerShell-terminal-output-alignment-17d6d73d3650811fa324e8a511b43a6b) by [Unito](https://www.unito.io)
=> Fix PowerShell terminal output alignment

src/install/installationManager.ts, src/main-process/comfyDesktopApp.ts, src/main-process/comfyInstallation.ts
Resolves separation of concerns issue: `VirtualEnvironment` is now a property of `ComfyInstallation`, rather than being created immediately prior to server startup.
NB: The venv object is re-instantiated in the `ComfyInstallation.basePath` setter.  If this is cause for concern, setting of basePath can be refactored to an explicit method.  Plan to refactor this into a cleaner configuration once the app restrucuring nears completeion.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-654-Refactor-Move-venv-as-child-of-installation-SoC-17e6d73d365081a594a2d6c9f63ca736) by [Unito](https://www.unito.io)
=> [Refactor] Move venv as child of installation (SoC)

src/constants.ts, src/handlers/appInfoHandlers.ts, src/main-process/comfyDesktopApp.ts, src/main.ts, src/preload.ts, tests/unit/handlers/appinfoHandlers.test.ts
- Move the get base path to app info handler to make it available during the entire app lifecycle
- Previously required that ComfyDesktopApp was instantiated.
- Add set base path, allowing change of the application path via API
- Frontend impl. will be added as part of startup validation
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-657-Add-base-path-management-API-17e6d73d3650810385c4f5b441fbbef0) by [Unito](https://www.unito.io)
=> Add base path management API

src/constants.ts, src/main_types.ts, src/preload.ts
- Adds the preload project portion of the validation PR, adding API methods under child objects:
- `Validation`
- `uv`
- Adds TS types to preload.
- Resolves a discard issue with an existing handler.
- Adds IPC channel constants
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-658-Preload-Add-startup-validation-API-17e6d73d3650818085b9fd03d726adce) by [Unito](https://www.unito.io)
=> [Preload] Add startup validation API

src/main.ts
- Requires https://github.com/Comfy-Org/ComfyUI_frontend/pull/2274
- Loads a basic static page with an indeterminate progress bar
- Reduces total time spent being tortured by Chromium's ludicrously bright pre-load window background
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-660-Show-basic-loading-screen-on-app-start-17e6d73d365081a59fc5cfdad3eb3ca5) by [Unito](https://www.unito.io)
=> Show basic loading screen on app start

src/constants.ts, src/handlers/AppHandlers.ts, src/main.ts, src/preload.ts
Add app quit API to allow a frontend quit keybind
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-667-Add-app-quit-API-to-allow-a-frontend-quit-keybind-17f6d73d36508198b7d6d2f6226d963a) by [Unito](https://www.unito.io)
=> Add app quit API to allow a frontend quit keybind

src/config/comfySettings.ts, src/main-process/comfyServer.ts, src/main.ts, src/services/telemetry.ts, tests/unit/comfySettings.test.ts, tests/unit/telemetry.test.ts
If metrics consent changes during pre-startup prompt process, write associated setting to comfy settings file, as the server will not have started yet. 
Adds `set` and `saveSettings` methods to `ComfySettings`, which are locked after the server starts.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-669-Write-metrics-consent-change-to-comfy-settings-file-1806d73d365081f298afd846641b9a70) by [Unito](https://www.unito.io)
=> Write metrics consent change to comfy settings file

src/install/installationManager.ts, src/main-process/comfyDesktopApp.ts, src/main-process/comfyInstallation.ts, src/main.ts, src/utils.ts, src/virtualEnvironment.ts
Requires:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/2253
- Any validation errors require a user response (which requires 2253).
Validates the following on startup:
- Installation base path
- Virtual environment
- Python functionality
- Required python packages
- git
- VC redistributable
Adds maintenance tasks available through IPC:
- Reset virtual environment (clears the .venv dir)
- Clear uv cache
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-616-Add-installation-validation-17b6d73d36508176891ce05bd03c70e5) by [Unito](https://www.unito.io)
=> Add installation validation

tests/assets/extra_models_paths/legacy-format.yaml, tests/assets/extra_models_paths/malformed.yaml, tests/assets/extra_models_paths/missing-base-path.yaml, tests/assets/extra_models_paths/multiple-sections.yaml, tests/assets/extra_models_paths/valid-config.yaml, tests/assets/extra_models_paths/wrong-type.yaml, tests/unit/comfyServerConfig.test.ts
Extends unit tests on `ComfyServerConfig` to include methods:
- `generateConfigFileContent`
- `getBaseModelPathFromRepoPath`
- `getBaseConfig`
- `readConfigFile`
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-679-Test-Add-ComfyServerConfig-unit-tests-1826d73d365081678f6af5b168f3111f) by [Unito](https://www.unito.io)
=> [Test] Add ComfyServerConfig unit tests

src/main.ts
Currently, when we close the app window you can re-open it from the mac doc. Which shows this error since the AppWindow is already destroyed.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-690-Fixed-Quit-app-on-mac-when-windows-are-closed-1826d73d365081ea8916ca5304a75797) by [Unito](https://www.unito.io)
=> Fixed: Quit app on mac when windows are closed.

src/main-process/appWindow.ts, src/models/DownloadManager.ts, src/services/cmCli.ts, src/services/telemetry.ts, src/shell/terminal.ts, src/store/desktopConfig.ts
Closes https://github.com/Comfy-Org/desktop/issues/648. Marks private fields only assigned in the constructor as `readonly`. [Linting rule](https://next.sonarqube.com/sonarqube/coding_rules?open=typescript%3AS2933&rule_key=typescript%3AS2933)
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-697-Mark-readonly-fields-as-readonly-1836d73d36508179b07fecc0315329ba) by [Unito](https://www.unito.io)
=> Mark readonly fields as readonly

tests/unit/comfyServerConfig.test.ts
This PR adds unit tests on remaining branches in `comfyServerConfig`, bringing to 100% coverage:
The untested function is marked as deprecated and never called.
Newly tested functions are:
- `exists`
- `writeConfigFile`
- `createConfigFile`
- `getConfigFile`
- `getConfigFromRepoPath`
- Test for final untested branch in `readBasePathFromConfig`
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-691-Test-Add-unit-tests-for-100-coverage-of-comfyServerConfig-1826d73d3650810b89f6c12875e7016a) by [Unito](https://www.unito.io)
=> [Test] Add unit tests for 100% coverage of comfyServerConfig

tests/unit/comfySettings.test.ts
This PR adds unit tests on remaining branches in `comfySettings`, bringing it to 100% coverage:
The remaining tests are on the error handling and null check in `saveSettings` (added here https://github.com/Comfy-Org/desktop/pull/669)
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-692-Test-Add-unit-tests-for-100-coverage-of-comfySettings-1826d73d3650814ab5d9ddc46ec1874a) by [Unito](https://www.unito.io)
=> [Test] Add unit tests for 100% coverage of comfySettings

tests/unit/comfyConfigManager.test.ts
This PR adds unit tests on remaining branches in `comfyConfigManager`, bringing to 100% coverage:
The last untested branch was handling `fs.mkdirSync` errors in `createComfyDirectories` method.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-693-Test-Add-unit-tests-for-100-coverage-of-comfyConfigManager-1826d73d3650811c811ff8d6bd1b64cb) by [Unito](https://www.unito.io)
=> [Test] Add unit tests for 100% coverage of comfyConfigManager

tests/unit/handlers/pathHandler.test.ts
This PR extends unit tests on `pathHandlers`, bringing it to 100% coverage:
Additionally, the tests are refactored to be easier to extend in the future. Currently, only the described behavior of each handler is being asserted.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-694-Test-Add-unit-tests-for-100-coverage-of-pathHandlers-1836d73d36508109b899c10b1c92693a) by [Unito](https://www.unito.io)
=> [Test] Add unit tests for 100% coverage of pathHandlers

package.json
Automated frontend update to 1.8.4
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-700-chore-Update-frontend-to-1-8-4-1836d73d365081e9a92ed15220505501) by [Unito](https://www.unito.io)
=> [chore] Update frontend to 1.8.4

src/main-process/appWindow.ts, src/main.ts, src/virtualEnvironment.ts
Utilize a single `install_flow:virtual_environment_create_end` event with properties indicating what the reason was.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-689-Track-quitting-and-virtual-env-skip-events-1826d73d365081078e84f18bcd251e1d) by [Unito](https://www.unito.io)
=> Track quitting and virtual env skip events.

eslint.config.js, tests/unit/comfySettings.test.ts, tests/unit/telemetry.test.ts, tests/unit/utils.test.ts
Updates es-lint rules:
- Disable no-unsafe-* and no-explicit-any rules in test files as it is often necessary to mock objects and functions, which can require using any types or unsafe assignments/accesses
- Enable [prefer-readonly](https://typescript-eslint.io/rules/prefer-readonly/) (ref: https://github.com/Comfy-Org/desktop/pull/697)
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-702-Update-ESLint-rules-1846d73d36508193a94edad0127d7736) by [Unito](https://www.unito.io)
=> Update ESLint rules

.env_example, src/main-process/appWindow.ts
- By default, DevTools no longer opens on app start with using a dev server
- Now controlled via env var
- Added to `.env_example`
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-704-Dev-Make-auto-open-of-DevTools-optional-1846d73d365081258578edf9f2b91fc5) by [Unito](https://www.unito.io)
=> [Dev] Make auto open of DevTools optional

tests/unit/install/installationManager.test.ts
This PR adds unit tests on installationManager `ensureInstalled` method, testing various installation validation scenarios.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-712-Test-Add-install-validation-unit-tests-1856d73d365081ed9d07eaedacf76a17) by [Unito](https://www.unito.io)
=> [Test] Add install validation unit tests

src/config/comfySettings.ts, src/install/installWizard.ts, src/main-process/comfyDesktopApp.ts, src/main-process/comfyInstallation.ts, src/preload.ts, src/virtualEnvironment.ts, tests/unit/comfySettings.test.ts
1. Added new settings for Python and PyPI mirrors:
- Added `PythonInstallMirror` and `PypiInstallMirror` to `DEFAULT_SETTINGS` and `ComfySettingsData` interface
- These settings allow configuring alternative mirrors for Python and PyPI package installations
2. Refactored `ComfyDesktopApp` and `ComfyInstallation`:
- Moved `ComfySettings` management from `ComfyDesktopApp` to `ComfyInstallation`
- Changed `ComfySettings` to be a property in `ComfyDesktopApp`
3. Enhanced `VirtualEnvironment`:
- Refactored constructor to accept an options object instead of individual parameters
- Added support for Python and PyPI mirrors through environment variables
- Updated default Python version handling
4. Updated `InstallWizard` to include mirror settings in the installation options
┆Issue is …
=> Add UV mirror settings

src/virtualEnvironment.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-714-BugFix-Don-t-set-env-var-on-empty-mirror-string-1856d73d365081b399b4c6ca1737beac) by [Unito](https://www.unito.io)
=> [BugFix] Don't set env var on empty mirror string

src/constants.ts, src/handlers/networkHandlers.ts, src/main.ts, src/preload.ts, src/utils.ts
The frontend won't be able to access remote mirrors because of CoRS policy. This PR exposes a electronAPI to check accessibility of url.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-711-Add-electronAPI-Network-canAccessUrl-1846d73d36508130a6cacfcf5e1d33bb) by [Unito](https://www.unito.io)
=> Add electronAPI.Network.canAccessUrl

src/main-process/appWindow.ts
- Classes in the app have no way to determine what page the browser is currently showing
- If we want to ensure we're on a specific page, we need to force navigate to the URL (awful UX, usually resets something)
- A type-safe check to determine if a page is already the current window URL
- Save the last requested page: frontend uses redirects, rendering this inaccurate
N.B. Split from larger PR on venv move.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-730-Allow-app-to-check-the-current-browser-location-1856d73d3650813c9cdeec66eb4661f0) by [Unito](https://www.unito.io)
=> Allow app to check the current browser location

scripts/resetInstall.js, tests/unit/comfyConfigManager.test.ts, tests/unit/comfyServer.test.ts, tests/unit/comfyServerConfig.test.ts, tests/unit/comfySettings.test.ts, tests/unit/handlers/AppHandlers.test.ts, tests/unit/handlers/appinfoHandlers.test.ts, tests/unit/handlers/pathHandler.test.ts, tests/unit/install/installationManager.test.ts, tests/unit/store/desktopConfig.test.ts, tests/unit/telemetry.test.ts, tests/unit/utils.test.ts, tsconfig.json, vite.base.config.ts
Avoids the relative path syntax. Replacing them with `@/`.
Follow-up: cleanup deep relative imports in the codebase.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-729-DevExperience-Add-root-path-syntax-support-1856d73d3650817885ddc1692f272f0c) by [Unito](https://www.unito.io)
=> [DevExperience] Add @/ root path syntax support

.github/workflows/debug_macos.yml, .github/workflows/publish_macos.yml
Use consistent node version (v20) for all builds.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-734-Use-node-v20-for-macos-builds-1856d73d365081d7abf6f88aced9e1bc) by [Unito](https://www.unito.io)
=> Use node v20 for macos builds

src/services/sentry.ts, src/services/telemetry.ts
All reports are opt-in by the user and done only with consent.
On Mixpanel error events, add event to `sentryQueue` then throw. When Sentry captures the thrown error, it generates the sentry event ID and adds the associated URL to all events in queue (multiple when there is a nested mixpanel scope). Sentry class then flushes the enriched events back to Mixpanel's `queue` for normal processing.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-739-Add-Sentry-URL-to-mixpanel-error-events-1866d73d3650813f9c80f5e74c920a04) by [Unito](https://www.unito.io)
=> Add Sentry URL to mixpanel error events

src/constants.ts, src/main-process/comfyDesktopApp.ts, src/preload.ts
The check `!ComfyServerConfig.exists()` is now invalid after the install process changes. Removing this api endpoint now as it is unused in the frontend.
=> [Cleanup] Remove unused API endpoint isFirstTimeSetup

src/config/comfySettings.ts, src/install/installWizard.ts, src/main-process/comfyInstallation.ts, src/preload.ts, src/virtualEnvironment.ts, tests/unit/comfySettings.test.ts
This PR allows frontend specify a torch mirror url for torch installation.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-743-Support-using-custom-torch-pip-mirror-1876d73d36508195b1bbf3e388764bb1) by [Unito](https://www.unito.io)
=> Support using custom torch pip mirror

.husky/pre-commit, src/virtualEnvironment.ts
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/2333#discussion_r1929091492
UV does not accept Pypi env variable. The Pypi mirror should be used as `index-url` when invoking `pip` command.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-751-Fix-pypi-mirror-usage-in-virtualEnvironment-ts-1896d73d365081cca547f12ef497f8a4) by [Unito](https://www.unito.io)
=> Fix pypi mirror usage in virtualEnvironment.ts

src/constants.ts, src/virtualEnvironment.ts
For frontend display purpose.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-752-Extract-hardcoded-torch-install-URL-to-global-constants-1896d73d365081a3b054e2126688c052) by [Unito](https://www.unito.io)
=> Extract hardcoded torch install URL to global constants

src/install/installationManager.ts, src/virtualEnvironment.ts
Adds logging to maintenance task wrappers.
N.B. These duplicate methods will be removed when #765 is resolved.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-766-Add-maintenance-task-logging-18a6d73d36508196bd96c956f49c4e6f) by [Unito](https://www.unito.io)
=> Add maintenance task logging

src/virtualEnvironment.ts
`--prerelease` is not a valid pip argument.
Ref:
- https://stackoverflow.com/questions/35131861/what-does-the-pre-option-in-pip-signify
- ![Screenshot 2025-01-29 at 10 34 43 AM](https://github.com/user-attachments/assets/a29475f3-a7a0-4d79-bd35-27d2c3f22e2a)
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-767-Fix-pip-prerelease-install-18a6d73d3650814b8e61fb179a08514c) by [Unito](https://www.unito.io)
=> Fix pip prerelease install

package.json, scripts/updateFrontend.js
Automated frontend update to 1.8.12: https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.8.12
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-790-chore-Update-frontend-to-1-8-12-18c6d73d36508127928df4e289b99e88) by [Unito](https://www.unito.io)
=> [chore] Update frontend to 1.8.12

.gitattributes, .github/workflows/ci.yaml, tests/unit/main-process/appWindow.test.ts
Was missing a mock for a function that was only hit on macos.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-804-Fixed-missing-mock-for-unit-test-on-MacOS-18f6d73d365081cfb28ae13774c2c82a) by [Unito](https://www.unito.io)
=> Fixed: missing mock for unit test on MacOS.

src/config/comfyServerConfig.ts, src/main-process/comfyServer.ts, tests/unit/comfyServer.test.ts, tests/unit/comfyServerConfig.test.ts
Since `--base-directory` was added to core, we can utilize that to avoid adding so many paths in `extra_model_config.yaml`. Most custom nodes utilize the `model_dir` in folder paths to add their own model directories. 
This PR changes:
- Add base_directory argument when starting ComfyUI to the base_path of the desktop application
- Remove model extra paths from the default newly created extra_model_config.yaml
- Add additional custom_nodes mapping so Manager will be added from the app resource folder, which is bundled with the application
```
desktop_patch:
custom_nodes: /...app resources folder
```
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-782-Use-base-directory-in-ComfyUI-to-resolve-model-import-issues-18b6d73d365081119102c71e8c4675fe) by …
=> Use --base-directory in ComfyUI to resolve model import issues.

src/install/installationManager.ts, src/services/telemetry.ts, tests/unit/telemetry.test.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-829-Add-tracking-for-python-mirror-urls-1916d73d36508132b40fc9e62b1adb5e) by [Unito](https://www.unito.io)
=> Add tracking for python mirror urls.

src/virtualEnvironment.ts
Remove the local cache. 
- Benefit from the global uv cache for all users of uv (eg. torch doesn't need to be downloaded again)
- Avoid issues where cache is not compatible on an external hard drive (eg. drives with exFat formatting)
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-828-Use-global-uv-cache-1916d73d365081648813edd818f8951a) by [Unito](https://www.unito.io)
=> Use global uv cache.

src/services/telemetry.ts, tests/unit/telemetry.test.ts
Previously was FIFO and that was a bug...
- Fix sending correct timestamp.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-838-Empty-telemetry-from-front-of-the-queue-1926d73d3650810ea658d17452fb87ea) by [Unito](https://www.unito.io)
=> Empty telemetry from front of the queue.

package.json
Could not revert previous PR for some reason on Github.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-842-Revert-ComfyUI-Manager-version-1926d73d36508137b60cc5b2b368aaa0) by [Unito](https://www.unito.io)
=> Revert ComfyUI-Manager version.

src/install/installationManager.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-846-Add-telemetry-for-installation-events-from-validation-page-1926d73d3650819493ded69032c5c23c) by [Unito](https://www.unito.io)
=> Add telemetry for installation events (from validation page).

package.json, yarn.lock
Forgot to update the cli version in: https://github.com/Comfy-Org/desktop/pull/885
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-886-Update-todesktop-cli-version-for-auto-updater-features-1976d73d3650817ea1aec66ebab16901) by [Unito](https://www.unito.io)
=> Update todesktop cli version for auto updater features.

package.json
Automated frontend update to 1.9.15: https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.9.15
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-893-chore-Update-frontend-to-1-9-15-1996d73d3650817fb9f0ee771ce924ff) by [Unito](https://www.unito.io)
=> [chore] Update frontend to 1.9.15

src/virtualEnvironment.ts
Only use the uv managed python-standalone. Not system Python, which can be unpredictable or corrupt.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-889-Only-use-managed-python-for-uv-1986d73d365081708cdbc521d3305ce3) by [Unito](https://www.unito.io)
=> Only use managed python for uv.

package.json, scripts/makeComfy.js, vite.base.config.ts
Sometimes we need to release a commit that has not made it to a ComfyUI stable release yet.
In this PR we are adding the ComfyUI branch [desktop-release-feb172025](https://github.com/comfyanonymous/ComfyUI/tree/refs/heads/desktop-release-feb172025), which includes the commit for https://github.com/comfyanonymous/ComfyUI/pull/6807 to fix installing in locations with special characters on Windows.
Full CI Run Complete
https://github.com/comfyanonymous/ComfyUI/actions/runs/13378074466
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-911-Add-support-for-bundling-cherry-picked-branches-in-Build-Process-19c6d73d3650810aa9e4f47dda8bd9c3) by [Unito](https://www.unito.io)
=> Add support for bundling cherry-picked branches in Build Process

assets/requirements/windows_cpu.compiled, assets/requirements/windows_nvidia.compiled, package.json, scripts/makeComfy.js, src/services/cmCli.ts, src/virtualEnvironment.ts
- Includes bug fixes from manager:
https://github.com/ltdrdata/ComfyUI-Manager/commit/488f023bdf49d6b85a00e230501eb009f5ffdbd9
- Fixed: migrating custom nodes: uses `restore-to` to fix importing custom nodes.
- Remove extra ComfyUI-Manager when migrating/importing from another ComfyUI install
- Updated requirements.compiled
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-912-Use-upstream-Manager-19c6d73d365081fe9711f9baf8bb81b6) by [Unito](https://www.unito.io)
=> Use upstream Manager.

.github/actions/build/todesktop/action.yml
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1051-Remove-patch-step-since-make-assets-already-runs-it-1b46d73d365081529d3af3bbb6c95a35) by [Unito](https://www.unito.io)
=> Remove patch step since make:assets already runs it.

src/install/installationManager.ts
When installation of requirements error out (it did on Windows with access denied error when installing new dependencies), don't have the user get stuck in the `desktop-update` page. 
Currently user will wait in the Desktop update spinner forever.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1055-Draft-Show-maintenance-page-when-1b46d73d365081d6a088c96f741fd026) by [Unito](https://www.unito.io)
=> Fixed: User gets stuck in Desktop Updating page when error occurs

src/main-process/appWindow.ts, src/main-process/comfyServer.ts, src/main.ts, src/utils.ts
Also fixed a bug where if the browser webContent is destroyed already, we should not send the event.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1056-Rotate-main-log-file-to-make-it-easier-to-debug-user-sessions-1b56d73d36508126b17cc2f217b1e806) by [Unito](https://www.unito.io)
=> Rotate main.log file to make it easier to debug user sessions.

src/handlers/pathHandlers.ts, tests/unit/handlers/pathHandler.test.ts
Only return "exists" when the directory is not empty.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1060-Check-if-directory-is-empty-before-installation-warning-1b76d73d365081bc8b2bef6d3bdc3cc7) by [Unito](https://www.unito.io)
=> Check if directory is empty before installation warning.

src/handlers/pathHandlers.ts, src/preload.ts, tests/unit/handlers/pathHandler.test.ts
- Have separate requirements for free space for mac and Windows (5gb vs 10gb)
- Replace OneDrive in the default install path for Windows
- Validate install path does not contain OneDrive
- Validate install path does not contain a non system drive (eg. Must be C:\ drive)
FE PR here: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3059
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1059-Install-Path-Validation-Improvements-1b66d73d365081f683a1c4e11dbbbbfb) by [Unito](https://www.unito.io)
=> Install Path Validation Improvements

package.json
- Automated minor version bump to: 0.4.31
- Triggers npm publish workflow of API types
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1067-API-Publish-types-for-version-0-4-31-1b96d73d36508173afdccc6d8e2503c9) by [Unito](https://www.unito.io)
=> [API] Publish types for version 0.4.31

src/handlers/pathHandlers.ts
Open a message box showing user there was an error.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1066-Check-response-of-shell-openPath-for-errors-1b96d73d365081c7b019f674da6a16e3) by [Unito](https://www.unito.io)
=> Check response of shell.openPath for errors.

.env_example, src/main.ts
Lets you use vue devtools from within the electron app devtools by specifying the path the the extension in your env vars
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1080-Add-support-for-loading-vue-devtools-extension-1c46d73d3650810999c2f531c863e3f1) by [Unito](https://www.unito.io)
=> Add support for loading vue devtools extension

src/constants.ts, src/desktopApp.ts, src/handlers/gpuHandlers.ts, src/preload.ts, tests/unit/handlers/gpuHandlers.test.ts
Adds TorchMirrorUrl.NightlyCuda as 'https://download.pytorch.org/whl/nightly/cu128'
Exposes CHECK_BLACKWELL IPC handler
Related: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3480
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1090-Support-Blackwell-GPUs-1d76d73d365081b98570ff6766a4c24f) by [Unito](https://www.unito.io)
=> Support Blackwell GPUs

README.md
Change `extra_model_config` to `extra_models_config`
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1099-Fix-typo-extra_model_config-in-README-1da6d73d36508125a32fdddb46fc8311) by [Unito](https://www.unito.io)
=> Fix typo `extra_model_config` in README

package.json
- Automated minor version bump to: 0.4.37
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1101-API-Publish-types-for-version-0-4-37-1da6d73d36508118817ad4588ae1beca) by [Unito](https://www.unito.io)
=> [API] Publish types for version 0.4.37

package.json, src/preload.ts
Oops, forgot to update the checkForUpdates() promise to include the version.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1102-Promise-version-in-checkForUpdates-1db6d73d3650814fb159c450ce455d1c) by [Unito](https://www.unito.io)
=> Promise version in checkForUpdates

package.json, src/preload.ts
Used to prevent todesktop from handling the update prompts since frontend already has a confirm dialog to prompt restart and install.
sorry about the pr/npm spam 😖
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1103-Allow-options-to-be-passed-to-checkForUpdates-1db6d73d365081f28c1ff0ba21ca477c) by [Unito](https://www.unito.io)
=> Allow options to be passed to checkForUpdates

src/services/telemetry.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1128-Patched-Check-user-consent-before-incrementing-property-1e06d73d365081a7a5a1df0548ea391f) by [Unito](https://www.unito.io)
=> Patched: Check user consent before incrementing property.

.github/workflows/ci.yaml, .github/workflows/debug_all.yml
- Added `.claude/**` and `CLAUDE.md` to paths-ignore in CI workflows that don't need to run for Claude configuration changes
- Updated `ci.yaml` (unit tests, linting, formatting) to skip Claude files
- Updated `debug_all.yml` (build testing) to skip Claude files
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1188-Ignore-Claude-configuration-files-in-CI-workflows-2096d73d36508115bd6ec3f3297b4074) by [Unito](https://www.unito.io)
=> Ignore Claude configuration files in CI workflows

assets/requirements/windows_cpu.compiled, assets/requirements/windows_nvidia.compiled, package.json, scripts/core-requirements.patch
- Updated ComfyUI from v0.3.38 to v0.3.40 with latest frontend version 1.21.7
- Updated all dependency files including core-requirements.patch and Windows compiled requirements
- Added new comfyui-embedded-docs package and updated workflow templates to v0.1.25
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1186-Bumping-ComfyUI-core-to-v0-3-40-2096d73d36508146b628d830ab1df9d3) by [Unito](https://www.unito.io)
=> Bumping ComfyUI core to v0.3.40

assets/requirements/macos.compiled, assets/requirements/windows_cpu.compiled, assets/requirements/windows_nvidia.compiled, package.json, scripts/core-requirements.patch
| Component     | Version               |
| ------------- | --------------------- |
| ComfyUI core  | [v0.3.48](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.48)       |
| Templates     | [v0.1.45](https://github.com/Comfy-Org/workflow_templates/releases/tag/v0.1.45)     |
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1240-Update-ComfyUI-core-to-v0-3-48-2436d73d3650814681a6c4bc08c4c2ed) by [Unito](https://www.unito.io)
=> Update ComfyUI core to v0.3.48
