Comfy-Org/desktop

src/preload.ts
Ref: https://github.com/Comfy-Org/desktop/blob/ac9196448147ef68255b918d8cbc381ead6934dd/src/terminal.ts#L41-L46
=> Fix inconsistent types on electronAPI.Terminal.restore

src/utils.ts
Adds a PowerShell check to ensure that users are not blocked from installing, if they do not have the (sadly deprecated) wmic.exe tool available on their device.
Resolves #378
=> Ensure NVIDIA users without wmic can install

package.json, src/handlers/pathHandlers.ts, src/main-process/comfyDesktopApp.ts
Requires https://github.com/Comfy-Org/ComfyUI_frontend/pull/1717
Update frontend to v1.5.0.
=> Load not supported page when hardware is not supported

src/utils.ts
Resolves issue in hardware validation causing GPU check to always pass.
=> Fix GPU check skipped

package.json
Includes fixes for: 
- Downloading models to the correct directory.
https://github.com/ltdrdata/ComfyUI-Manager/commit/9e4461719966d906745d1129169ad07a68d51c81
=> Update to latest manager.

src/config/comfyServerConfig.ts
https://github.com/ltdrdata/ComfyUI-Manager/commit/9e4461719966d906745d1129169ad07a68d51c81
=> Enable downloading models from Manager into base_path.

.github/actions/build/windows/todesktop/action.yml, .github/workflows/publish_all.yml
Forgot to add default value for STAGING in todesktop workflow action.
=> Fixed: Publish all passes staging = false.

forge.env.d.ts, src/virtualEnvironment.ts
Forces the python subprocess to use utf8
#425
=> Force python to output utf8

src/main-process/comfyDesktopApp.ts
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1812
Still allow user install in case our device detection logic has bugs.
=> Allow user skip device detection

package.json, scripts/updateFrontend.js
Run `yarn update:frontend` to update frontend version in package.json to latest.
=> Add frontend update script to automate sync with latest frontend release

package.json
=> Upgrade comfy to 0.3.7

src/main-process/comfyServer.ts, src/main.ts
=> Fix .env CPU flag ignored

package.json
Includes this fix: https://github.com/Comfy-Org/ComfyUI_frontend/pull/1831
=> Update frontend: 1.5.9

package.json
Automated frontend update to 1.5.10
=> [chore] Update frontend to 1.5.10

src/constants.ts, src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts, src/preload.ts
Adds native context menu controls for all text area and inputs of type="text"
=> Add native context menu

src/main-process/comfyServer.ts
Required for https://github.com/Comfy-Org/ComfyUI_frontend/pull/1846
=> Enh: add more server side arguments

package.json
Automated frontend update to 1.5.14
=> [chore] Update frontend to 1.5.14

package.json
Includes many improvements and bug fixes around virtual env creation since 0.5.4. https://github.com/astral-sh/uv/releases
=> Update uv to 0.5.8

package.json
Automated version bump to 0.3.34
=> 0.3.34(types)

src/handlers/appInfoHandlers.ts, src/main-process/comfyDesktopApp.ts, tests/unit/handlers/appinfoHandlers.test.ts
- Fixes issue where GPU was not pre-selected during install, even if properly detected
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-501-Fix-GPU-preselection-15f6d73d365081e79cbfd2c735d27243) by [Unito](https://www.unito.io)
=> Fix GPU preselection

package.json
Adds hunyuan video support.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-537-Update-comfyuI-to-0-3-8-1616d73d365081779a4bfd1ae2da5f8d) by [Unito](https://www.unito.io)
=> Update comfyuI to 0.3.8

package.json
https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.9
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-547-Update-ComfyUI-to-0-3-9-1626d73d3650816c84ccfd73a8555aa7) by [Unito](https://www.unito.io)
=> Update ComfyUI to 0.3.9

src/main-process/comfyDesktopApp.ts, src/services/cmCli.ts
- Lints code
- Minor refactor (faster/cleaner than trying to fix one fo the errors without changing behaviour)
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-556-Fix-eslint-errors-1666d73d36508118b8abc266380b0ef3) by [Unito](https://www.unito.io)
=> Fix eslint errors

package.json
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-557-0-4-3-types-1666d73d365081348a05f09ed11f99ad) by [Unito](https://www.unito.io)
=> 0.4.3(types)

package.json
Automated version bump to 0.4.7
=> 0.4.7(types)

package.json
Automated frontend update to 1.7.8
=> [chore] Update frontend to 1.7.8

package.json
Automated version bump to 0.4.8
=> 0.4.8(types)

README.md
=> nit: Fix format

src/main-process/comfyDesktopApp.ts, src/main.ts
This PR is part of larger effort to sort out install time dependency issues.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-641-Refactor-Make-ComfyDesktopApp-own-ComfyInstallation-17d6d73d3650811592daceca6af41ead) by [Unito](https://www.unito.io)
=> [Refactor] Make ComfyDesktopApp own ComfyInstallation

package.json
https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.11
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-644-Update-comfyui-version-to-0-3-11-Cosmos-17d6d73d365081c6bd68d25a55e7c899) by [Unito](https://www.unito.io)
=> Update comfyui version to 0.3.11 (Cosmos).

src/services/telemetry.ts
Closes https://github.com/Comfy-Org/desktop/issues/637
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-640-Cache-gpu-information-17d6d73d3650811ab72acd1808940d9d) by [Unito](https://www.unito.io)
=> Cache gpu information.

package.json
Automated version bump to 0.4.9
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-659-0-4-9-types-17e6d73d365081039079c2aefdb2bd9d) by [Unito](https://www.unito.io)
=> 0.4.9(types)

package.json, yarn.lock
Automated version bump to 0.4.10
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-665-0-4-10-types-17e6d73d3650816fa101e049bbdceccd) by [Unito](https://www.unito.io)
=> 0.4.10(types)

package.json
Automated frontend update to 1.7.14
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-666-chore-Update-frontend-to-1-7-14-17f6d73d3650813397b0c639f47f137c) by [Unito](https://www.unito.io)
=> [chore] Update frontend to 1.7.14

package.json
Automated version bump to 0.4.11
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-668-0-4-11-types-17f6d73d3650813e8ed4f00fc2cfb50d) by [Unito](https://www.unito.io)
=> 0.4.11(types)

src/services/telemetry.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-677-Move-metric-log-to-debug-severity-1826d73d365081ed9e51ddf647393166) by [Unito](https://www.unito.io)
=> Move metric log to debug severity.

tests/unit/comfySettings.test.ts
Adds test cases to comfySettings tests to include more common branches currently already handled by the class, including:
- file read error
- null/undefined values
- invalid JSON 
- Also includes cases for common types in comfy settings file: primitive type, reference type, nested object
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-682-Test-Add-comfySettings-unit-tests-1826d73d365081249b1dd12555257cd1) by [Unito](https://www.unito.io)
=> [Test] Add comfySettings unit tests

src/handlers/pathHandlers.ts, src/main-process/appWindow.ts, src/main-process/comfyDesktopApp.ts
This PR fixes some floating promises:
- add await
- add log to promise chain
Also removes redundant use of await on a return values (creates extra micro task).
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-695-Fix-floating-promises-1836d73d365081dc8495ca778fca5e1a) by [Unito](https://www.unito.io)
=> Fix floating promises

src/install/installationManager.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-705-Add-telemetry-for-installation-validation-1846d73d365081fba692e92200f69f4f) by [Unito](https://www.unito.io)
=> Add telemetry for installation validation

tests/unit/handlers/AppHandlers.test.ts, tests/unit/handlers/appinfoHandlers.test.ts
This PR adds unit tests on all modules in `src/handlers`:
=> [Test] Add unit tests on handlers

src/handlers/AppHandlers.ts, src/handlers/appInfoHandlers.ts, src/handlers/networkHandlers.ts, src/handlers/pathHandlers.ts, src/main.ts, tests/unit/handlers/AppHandlers.test.ts, tests/unit/handlers/appinfoHandlers.test.ts, tests/unit/handlers/pathHandler.test.ts
Remove unnecessary class wrappers.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-716-Refactor-Remove-unnecessary-wrapper-class-on-handlers-1856d73d365081d999dbd36c8fdcb254) by [Unito](https://www.unito.io)
=> [Refactor] Remove unnecessary wrapper class on handlers

package.json
Automated version bump to 0.4.15
=> 0.4.15(types)

package.json
Follow-up on https://github.com/Comfy-Org/desktop/pull/633
https://github.com/Comfy-Org/desktop/pull/633 moved the lint-staged to a standalone config script in https://github.com/Comfy-Org/desktop/blob/main/lint-staged.config.js
=> [Cleanup] Remove unnecessary lint-staged entry in package.json

src/install/installationManager.ts, src/main-process/comfyDesktopApp.ts
- Virtual environment creation is called on each app start, just before server init
- Immediately returns if directory is present
- Made redundant by app maintenance / startup validation
- Moves venv creation from app startup to installation logic
- Minimal PR - moves code as-is
- Clean up / refactoring can be handled separtately
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-737-Remove-virtual-environment-creation-from-server-start-1856d73d365081749fc6f3381dd56ebe) by [Unito](https://www.unito.io)
=> Remove virtual environment creation from server start

src/virtualEnvironment.ts
This PR refactors torch install args logic into separate functions for easier configurations in follow-up PRs.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-738-Refactor-Construct-torch-install-args-1866d73d3650819db308e986de554b9d) by [Unito](https://www.unito.io)
=> [Refactor] Construct torch install args

package.json
Automated version bump to 0.4.16
=> 0.4.16(types)

src/virtualEnvironment.ts
Requires https://github.com/Comfy-Org/ComfyUI_frontend/pull/2367
The calculation of pytorch `index-url` is now handled by frontend. Allowing users to overwrite the index-url if they prefer another torch setup.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-757-Use-frontend-configured-torch-index-url-18a6d73d3650816bb8ccf109fa6cb55a) by [Unito](https://www.unito.io)
=> Use frontend configured torch index-url

package.json, scripts/updateFrontend.js
Automated frontend update to 1.8.9
=> [chore] Update frontend to 1.8.9

package.json
Contains base path cli arg that we need.
=> Update ComfyUI to v0.3.13

src/config/comfySettings.ts, src/install/installWizard.ts
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/blob/52e42b5339e05d9ebc63896db9f5debeb7f0bc8f/src/extensions/core/electronAdapter.ts#L58-L79
=> Fix misaligned setting ids for UV mirrors

src/config/comfySettings.ts, src/install/installWizard.ts
Reverts Comfy-Org/desktop#773
Reason: fails compile.
=> Revert "Fix misaligned setting ids for UV mirrors"

src/config/comfySettings.ts, src/install/installWizard.ts, src/main-process/comfyInstallation.ts, tests/unit/comfySettings.test.ts
Reland #773
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-775-Reland-Fix-misaligned-mirror-setting-ids-18a6d73d3650812ab7d0cd813f40c269) by [Unito](https://www.unito.io)
=> [Reland] Fix misaligned mirror setting ids

src/virtualEnvironment.ts
When `Comfy-Desktop.UV.TorchInstallMirror` is not set explicitly, fallback to default mirror based on selected device.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-776-Fallback-to-default-torch-mirror-on-default-setting-value-18a6d73d365081568cbbe580ba1626c6) by [Unito](https://www.unito.io)
=> Fallback to default torch mirror on default setting value

package.json
Automated frontend update to 1.8.10
=> [chore] Update frontend to 1.8.10

package.json
Automated frontend update to 1.8.11
=> [chore] Update frontend to 1.8.11

package.json
Remove uv dependency for now.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-837-Update-Manager-commit-1926d73d365081ad8f66e32db662c096) by [Unito](https://www.unito.io)
=> Update Manager commit

package.json
Lumina 2 support.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-843-ComfyUI-v0-3-14-1926d73d365081ed802ed21d6b13f8b4) by [Unito](https://www.unito.io)
=> ComfyUI v0.3.14

package.json
Automated frontend update to 1.9.6
=> [chore] Update frontend to 1.9.6

src/main-process/appWindow.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-848-Change-window-init-logic-to-always-place-window-at-0-0-at-start-1926d73d365081889de3e01f97ad0c7e) by [Unito](https://www.unito.io)
=> Change window init logic to always place window at 0,0 at start

src/main-process/comfyDesktopApp.ts, tests/unit/main-process/comfyDesktopApp.test.ts, todesktop.json
https://www.npmjs.com/package/@todesktop/cli#updateurlbase---optional-string
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-885-Add-todesktop-custom-updater-url-1966d73d36508152a819fec233614746) by [Unito](https://www.unito.io)
=> Add todesktop custom updater url.

package.json
Uses a cherry-pick branch that has this PR: https://github.com/comfyanonymous/ComfyUI/pull/6885
[CI Run](https://github.com/comfyanonymous/ComfyUI/actions/runs/13425158159)
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-962-Cherry-pick-branch-Normalize-paths-in-extra_model_paths-1a06d73d36508179ac70c15c03fd2366) by [Unito](https://www.unito.io)
=> Cherry-pick branch: Normalize paths in extra_model_paths

package.json
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-999-Update-ComfyUI-to-v0-3-17-1a66d73d365081c594d9cad521359ffc) by [Unito](https://www.unito.io)
=> Update ComfyUI to v0.3.17

package.json
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1001-Update-ComfyUI-to-v0-3-18-1a76d73d3650812dac11fe0bee69d9ed) by [Unito](https://www.unito.io)
=> Update ComfyUI to v0.3.18

todesktop.json
Size increased a lot after the template workflows were added.
=> Increase size limit for ToDesktop uploads.

package.json
Add new China uv mirror.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1015-Frontend-v1-10-18-1ad6d73d36508125940fdddf51a5cf41) by [Unito](https://www.unito.io)
=> Frontend v1.10.18

package.json
Add support for Hunyuan i2v.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1027-Update-ComfyUI-to-v0-3-23-1ae6d73d36508181a860c0692531e3e4) by [Unito](https://www.unito.io)
=> Update ComfyUI to v0.3.23

package.json
Fixed desktop bug for Manager.
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1040-Update-Manager-commit-1b26d73d3650815ba7cef87ee9b8c382) by [Unito](https://www.unito.io)
=> Update Manager commit.

package.json
Fixes registry node installs.
https://github.com/ltdrdata/ComfyUI-Manager/commit/402e2c384f338d0ed0a7fb19caa93f29a0dc35fd
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1048-Update-ComfyUI-Manager-1b36d73d3650815eb7e5c811f0cd2d33) by [Unito](https://www.unito.io)
=> Update ComfyUI Manager

package.json
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1071-Update-ComfyUI-to-v0-3-27-1be6d73d365081908e1ee0db91bad684) by [Unito](https://www.unito.io)
=> Update ComfyUI to v0.3.27

package.json
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1072-Remove-core-branch-1be6d73d3650815983ffc4dbe46483ca) by [Unito](https://www.unito.io)
=> Remove core branch.

scripts/core-requirements.patch
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1073-Update-patch-to-update-requirements-1be6d73d365081ff83b6c33ec24ea7d4) by [Unito](https://www.unito.io)
=> Update patch to update requirements.

package.json
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1085-Bump-FE-to-1-15-13-1d56d73d365081d48497c322210ac089) by [Unito](https://www.unito.io)
=> Bump FE to 1.15.13

package.json, scripts/core-requirements.patch
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1086-Bump-core-0-3-28-1d56d73d365081d8a944f15462318c78) by [Unito](https://www.unito.io)
=> Bump core 0.3.28

package.json, scripts/core-requirements.patch, src/virtualEnvironment.ts
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1091-Add-change-to-install-templates-1d86d73d365081f7a160c1b5de7f7dde) by [Unito](https://www.unito.io)
=> Add change to install templates.

package.json
Publish types library for https://github.com/Comfy-Org/desktop/pull/1090
=> 0.4.36 (Types)

assets/requirements/windows_cpu.compiled, assets/requirements/windows_nvidia.compiled, scripts/core-requirements.patch
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1100-Update-wanfun-templates-1da6d73d365081f6b19cd7d47cc41516) by [Unito](https://www.unito.io)
=> Update wanfun templates.

package.json, src/handlers/AppHandlers.ts, src/preload.ts, tests/unit/handlers/AppHandlers.test.ts
Related: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3723
Resolves #1104
=> Add toasts for update check

package.json, scripts/core-requirements.patch
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1147-API-node-dependencies-1eb6d73d36508146852eefe16421b7c7) by [Unito](https://www.unito.io)
=> API node dependencies.

.claude/commands/bump-stable.md, CLAUDE.md
- Added CLAUDE.md with comprehensive project instructions and development guidelines for Claude Code
- Added .claude/ directory with project-specific commands and configuration
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1187-Add-Claude-Code-configuration-files-2096d73d3650817db304cd4ad21368d2) by [Unito](https://www.unito.io)
=> Add Claude Code configuration files

assets/requirements/macos.compiled, assets/requirements/windows_cpu.compiled, assets/requirements/windows_nvidia.compiled, package.json, scripts/core-requirements.patch
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1232-Update-ComfyUI-to-v0-3-46-23e6d73d365081f0b1c0df96ce3dcff6) by [Unito](https://www.unito.io)
=> Update ComfyUI to v0.3.46

.claude/commands/bump-stable.md
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1236-Add-macos-compiled-to-claude-code-command-23f6d73d365081e785cfeecea8aecf9f) by [Unito](https://www.unito.io)
=> Add macos.compiled to claude code command.

package.json
┆Issue is synchronized with this [Notion page](https://www.notion.so/PR-1279-Update-desktop-to-v0-4-67-and-ComfyUI-to-v0-3-34-25d6d73d365081679f40fbda234128af) by [Unito](https://www.unito.io)
=> Update desktop to v0.4.67 and ComfyUI to v0.3.34
